### ISSUE TITLE
Nice, but too many clicks

### ISSUE THREAD

**Issue by dmenne** [aschinchon/pleasing-ratio-project#1]
- Three clicks are required ... One is enough, otherwise subjects are bored.
- Bias: after first click, the last selection is still active
- Always use forced choice in psychometry. Allowing a "don't know" strongly reduces discriminator power.

**Comment by aschinchon** [comment]
Thanks,

+ Actually two clicks are required, the third one is to play again or to go to results. I honestly think two clicks is not too much but I will think about it
+ Why do you think it may cause a bias?
+ I think it is quite difficult to choose between two extremely similar ratios. In addition, if there is a winner ratio, it will win independently of allowing a "don't know" option, don't you think so?

**Comment by dmenne** [comment]
- Going to the results is a separate menu item, and it is easily visible. And yes, any action is too much in psychometry, your subject should respond "unconsciously" and quickly. 
- Any predefined choice is a bias. 
- No, it is a well known fact that close to the threshold the decision is much better than "consiously" know. Forced choice is the accepted standard, the discussion to use "don't know" was settled about 1970. 
- Even better: let users click on rectangles, so remove the buttons. Any mental redirection stops the flow of unconsciousness.

I have been teaching psychophysiology in university/research since 1974, so I am aware that these questions come up in every generation...

**Comment by aschinchon** [comment]
+ I removed the "I'm not sure" option

Thanks
